// app/layout.jsx

"use client";

import "./globals.css"; // Import global styles
import Header from "./components/Header"; // Import a Header component
import Footer from "./components/Footer"; // Import a Footer component

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
